- hosts: 192.168.158.239
  tasks:
   - name: Set Timezone
     copy: src=/usr/share/zoneinfo/Asia/Shanghai dest=/etc/localtime remote_src=yes
   
   - name: nproc
     lineinfile:
       dest: "{{ item.file }}"
       regexp: "{{ item.match }}"
       line: "{{ item.value }}"
       insertafter: "{{ item.match }}"
     with_items:
       - {"file": "/etc/security/limits.d/20-nproc.conf","match": '\*\s*soft\s*nproc(.+)*$', "value": "* soft nproc 20480"}
     when: ansible_distribution_major_version == "7"
   
   - name: Modify conf
     lineinfile:
       dest: '{{ item.file }}'
       regexp: '{{ item.match }}'
       line: '{{ item.value }}'
       insertafter: '{{ item.match }}'
     with_items:
       - {"file": "/etc/pam.d/system-auth","match": 'password\s*requisite[\s|\S]*', "value": "password    requisite    pam_cracklib.so try_first_pass retry=3 dcredit=-1 lcredit=-1 ucredit=-1 ocredit=-1 minlen=8"}
       - {"file": "/etc/pam.d/system-auth","match": 'password\s*sufficient\s*pam_unix.so', "value": "password    sufficient    pam_unix.so md5 shadow nullok try_first_pass use_authtok remember=5"}
       - {"file": "/etc/login.defs","match": 'PASS_MAX_DAYS\s*[0-9(\+)]', "value": "PASS_MAX_DAYS 90"}
       - {"file": "/etc/login.defs","match": 'PASS\_MIN\_LEN\s*[0-9(\+)]', "value": "PASS_MIN_LEN 8"}
       - {"file": "/etc/login.defs","match": 'PASS\_MIN\_DAYS\s*[0-9(\+)]', "value": "PASS_MIN_DAYS 10"}
       - {"file": "/etc/login.defs","match": 'PASS_WARN_AGE\s*[0-9(\+)]', "value": "PASS_WARN_AGE 30"}
       - {"file": "/etc/login.defs","match": 'UMASK\s*[0-9(\+)]', "value": "UMASK 027"}
       - {"file": "/etc/ssh/sshd_config","match": 'Banner\s*/etc/ssh_banner', "value": "Banner /etc/ssh_banner"}
       - {"file": "/etc/rsyslog.conf","match": 'cron\.\*\s*', "value": 'cron.* /var/log/cron'}
       - {"file": "/etc/rsyslog.conf","match": '\*.info;mail.none;authpriv.none;cron.none[\s|\S]*', "value": '*.info;mail.none;authpriv.none;cron.none;local3.info.none /var/log/adm_messages'}
       - {"file": "/etc/rsyslog.conf","match": '\*\.err;kern.debug;daemon.notice[\s|\S]*', "value": '*.err;kern.debug;daemon.notice /var/log/adm_messages'}
       - {"file": "/etc/rsyslog.conf","match": 'authpriv\.\*[\s|\S]*', "value": 'authpriv.* /var/log/secure'}
       - {"file": "/etc/profile","match": 'umask\s*[0-9(\+)]', "value": "umask 027"}
       - {"file": "/etc/profile","match": '\s*TMOUT\s*=', "value": "TMOUT=300"}
       - {"file": "/etc/security/limits.conf","match": '\*\s*soft\s*core\s*', "value": "* soft core 0"}
       - {"file": "/etc/security/limits.conf","match": '\*\s*hard\s*core\s*', "value": "* hard core 0"}
       - {"file": "/etc/security/limits.conf","match": '\*\s*soft\s*nofile', "value": "* soft nofile 65536"}
       - {"file": "/etc/security/limits.conf","match": '\*\s*hard\s*nofile', "value": "* hard nofile 65536"}
       - {"file": "/etc/sysctl.conf","match": 'vm.swappiness', "value": "vm.swappiness=0"}
       - {"file": "/etc/sysctl.conf","match": 'net.ipv4.tcp_syncookies', "value": "net.ipv4.tcp_syncookies=1"}
       - {"file": "/etc/sysctl.conf","match": 'net.ipv4.tcp_fin_timeout', "value": "net.ipv4.tcp_fin_timeout=30"}
       - {"file": "/etc/sysctl.conf","match": 'net.ipv4.tcp_max_syn_backlog', "value": "net.ipv4.tcp_max_syn_backlog=10240"}
       - {"file": "/etc/sysctl.conf","match": 'net.ipv4.tcp_max_tw_buckets', "value": "net.ipv4.tcp_max_tw_buckets=20480"}
       - {"file": "/etc/sysctl.conf","match": 'net.ipv4.tcp_tw_reuse', "value": "net.ipv4.tcp_tw_reuse=1"}
       - {"file": "/etc/sysctl.conf","match": 'net.ipv4.tcp_tw_recycle', "value": "net.ipv4.tcp_tw_recycle=0"}
       - {"file": "/etc/sysctl.conf","match": 'net.netfilter.nf_conntrack_max', "value": "net.netfilter.nf_conntrack_max=524288"}
       - {"file": "/etc/sysctl.conf","match": 'vm.max_map_count', "value": "vm.max_map_count=262144"}
       - {"file": "/etc/sysctl.conf","match": 'net.core.rmem_max', "value": "net.core.rmem_max=12492800"}
       - {"file": "/etc/sysconfig/selinux","match": '\s*SELINUX\s*=', "value": "SELINUX=disabled"}
       - {"file": "/etc/selinux/config","match": '\s*SELINUX\s*=', "value": "SELINUX=disabled"}
       - {"file": "/etc/selinux/config","match": '\s*SELINUX\s*=', "value": "SELINUX=disabled"}
       - {"file": "/etc/security/limits.conf","match": '\*\s*soft\s*core\s*', "value": "* soft core 0"}
       - {"file": "/etc/security/limits.conf","match": '\*\s*hard\s*core\s*', "value": "* hard core 0"}
       - {"file": "/etc/security/limits.conf","match": '\*\s*soft\s*nofile', "value": "* soft nofile 65536"}
       - {"file": "/etc/security/limits.conf","match": '\*\s*hard\s*nofile', "value": "* hard nofile 65536"}
       - {"file": "/etc/sysctl.conf","match": 'vm.max_map_count', "value": "vm.max_map_count=262144"}
